export const data = {
	en: {
		headings: {
			cv: "",
			personalData: "",
			professionalExperience: "",
			education: "",
			itExperience: "",
			additionalExperience: "",
		},
		personalData: {
			pob: {
				title: "",
				value: "",
			},
			nationality: {
				title: "",
				value: "",
			},
			maritalStatus: {
				title: "",
				value: "",
			},
			name: "Felix Grafschmidt",
			street: "Feldstrasse 13",
			city: "5415 Nussbaumen AG, Switzerland",
			mail: "felix.grafschmidt@gmail.com",
			phone: "(+41) 774 286063",
		},
		professionalExperience: [
			{
				timespan: "",
				employer: "",
				position: "",
				tasks: [],
			},
		],
		education: [
			{
				timespan: "",
				institution: "",
				topic: "",
				additionalInformation: [],
				degree: "",
			},
		],
		itExperience: {
			feTitle: "Frontend",
			beTitle: "Backend",
			frontend: ["Nuxt.js", "Vue.js", "TypeScript", "JavaScript", "CSS", "jQuery", "tailwindss"],
			backend: [
				"Nuxt.js",
				"Spring Boot",
				"Java",
				"TypeScript",
				"JavaScript",
				"Python",
				"Adobe ColdFusion",
				"MSSQL",
				"Docker",
				"Kubernetes",
				"ArgoCD",
				"Vaadin",
				"redis",
			],
		},
		additionalExperience: [
			{
				title: "languages",
				values: [],
			},
		],
	},
	de: {
		headings: {
			cv: "Lebenslauf",
			personalData: "Persönliche Daten",
			professionalExperience: "Berufserfahrung",
			education: "Bildungsweg",
			itExperience: "IT-Kenntnisse",
			additionalExperience: "Weitere Fähigkeiten und Kenntnisse",
		},
		personalData: {
			pob: {
				title: "Geburtsdatum/-ort",
				value: "01.08.1994 in Essen in Deutschland",
			},
			nationality: {
				title: "Nationalität",
				value: "Deutschland",
			},
			maritalStatus: {
				title: "Zivilstand",
				value: "verheiratet",
			},
			name: "Felix Grafschmidt",
			street: "Feldstrasse 13",
			city: "5415 Nussbaumen AG, CH",
			mail: "felix.grafschmidt@gmail.com",
			phone: "(+41) 774 286063",
		},
		professionalExperience: [
			{
				timespan: "08.2021 – heute",
				employer: "Interhome Group – HHD AG, Opfikon",
				position: "Webentwickler",
				tasks: [
					"Entwicklung, Betreuung, Wartung und Optimierung der Unternehmenswebseite sowie interner Web-Applikationen",
					"Entwurf und Entwicklung webbasierter Softwarelösungen",
					"Planung von Design und Architektur",
					"Entwicklung und Anbindung von Datenbanken",
					"Analyse, Aufwandseinschätzung und Umsetzung von Business Anforderungen",
					"Deployment und Betrieb innerhalb einer Unix-basierten Serverumgebung",
					"Support bei Fragen und Problemen bezüglich der entwickelten Webseiten",
				],
			},
			{
				timespan: "08.2019 – 07.2021",
				employer: "Interhome Group – HHD GmbH, Freiburg in Deutschland",
				position: "Softwareentwickler",
				tasks: [
					"Entwicklung, Betreuung, Wartung und Optimierung der Unternehmenswebseite sowie interner Web-Applikationen",
					"Entwurf und Entwicklung webbasierter Softwarelösungen",
					"Planung von Design und Architektur",
					"Entwicklung und Anbindung von Datenbanken",
					"Analyse, Aufwandseinschätzung und Umsetzung von Business Anforderungen",
					"Deployment und Betrieb innerhalb einer Unix-basierten Serverumgebung",
					"Support bei Fragen und Problemen bezüglich der entwickelten Webseiten",
				],
			},
			{
				timespan: "08.2017 – 07.2019",
				employer: "Interhome Group – HHD GmbH, Freiburg in Deutschland",
				position: "Trainee | Softwareentwicklung",
				tasks: [
					"Entwicklung, Betreuung, Wartung und Optimierung der Unternehmenswebseite sowie interner Web-Applikationen",
					"Entwurf und Entwicklung webbasierter Softwarelösungen",
					"Planung von Design und Architektur",
					"Entwicklung und Anbindung von Datenbanken",
					"Analyse, Aufwandseinschätzung und Umsetzung von Business Anforderungen",
					"Deployment und Betrieb innerhalb einer Unix-basierten Serverumgebung",
					"Support bei Fragen und Problemen bezüglich der entwickelten Webseiten",
				],
			},
			{
				timespan: "10.2016 – 03.2017",
				employer: "Albert-Ludwigs-Universität Freiburg, Freiburg in Deutschland",
				position: "Studentische Hilfskraft und Tutor | Seminar zur Vorlesung 'Einführung in die Formale Logik'",
				tasks: [],
			},
			{
				timespan: "10.2015 – 02.2016",
				employer: "Albert-Ludwigs-Universität Freiburg, Freiburg in Deutschland",
				position: "Studentische Hilfskraft und Tutor | Seminar zur Vorlesung 'Einführung in die Formale Logik'",
				tasks: [],
			},
		],
		education: [
			{
				timespan: "10.2014 – 09.2017",
				institution: "Albert-Ludwigs-Universität Freiburg, Freiburg in Deutschland",
				topic: "Studiengang: Philosophie",
				additionalInformation: ["Schwerpunkte: Formale Logik und Sprachphilosophie", "Nebenfach: Anglistik", "Abschlussnote: 1,9"],
				degree: "Abschluss: Bachelor of Arts (B.A.)",
			},
			{
				timespan: "10.2013 – 09.2014",
				institution: "Albert-Ludwigs-Universität Freiburg, Freiburg in Deutschland",
				topic: "Studiengang: Informatik",
				additionalInformation: [],
				degree: "",
			},
			{
				timespan: "08.2005 – 07.2013",
				institution: "Gymnasium Borbeck, Essen in Deutschland",
				topic: "",
				additionalInformation: ["Abschlussnote: 1,8"],
				degree: "Abschluss: Allgemeine Hochschulreife",
			},
		],
		itExperience: {
			feTitle: "Frontend",
			beTitle: "Backend",
			frontend: ["Nuxt.js", "Vue.js", "TypeScript", "JavaScript", "CSS", "jQuery", "tailwindss"],
			backend: [
				"Nuxt.js",
				"Spring Boot",
				"Java",
				"TypeScript",
				"JavaScript",
				"Python",
				"Adobe ColdFusion",
				"MSSQL",
				"Docker",
				"Kubernetes",
				"ArgoCD",
				"Vaadin",
				"redis",
			],
		},
		additionalExperience: [
			{
				title: "Sprachen",
				values: [
					"Deutsch, Muttersprache (C2)",
					"Englisch, verhandlungssicher (C1/C2)",
					"Latein, grosses Latinum",
					"Französisch, Grundkenntnisse (A2)",
				],
			},
		],
	},
};

export type Data = typeof data;
