export const data = {
	en: {
		headings: {
			title: "Full Stack Web Developer",
			summary: "Executive Summary",
			cv: "Curriculum Vitae",
			personalData: "Personal Information",
			professionalExperience: "Professional Experience",
			education: "Education",
			itExperience: "IT Skills",
			additionalExperience: "Additional Skills and Qualifications",
		},
		cover: {
			summary:
				"Highly motivated Web Developer with 6+ years of professional experience. Proficient in designing, supporting, and optimising full-stack company websites and internal web applications. Adept at conducting business requirement analyses and implementing server operations. Dedicated to delivering high-quality digital solutions. In possession of conceptual strength and a flexible, hands-on approach while relying on excellent interpersonal skills that allows for seamless integration into any team.",
			appendixTitle: "Appendix",
			appendix: ["Curriculum Vitae"],
		},
		personalData: {
			pob: {
				title: "Date and place of birth",
				value: "August 01, 1994, Essen in Germany",
			},
			nationality: {
				title: "Nationality",
				value: "Germany",
			},
			maritalStatus: {
				title: "Marital status",
				value: "married",
			},
			name: "Felix Grafschmidt",
			city: "Winterthur, Switzerland",
			mail: "felix.grafschmidt@gmail.com",
			phone: "(+41) 774 286063",
		},
		professionalExperience: [
			{
				timespan: "08/2021 – ongoing",
				employer: "Interhome Group – HHD AG, Opfikon",
				position: "Web Developer",
				tasks: [
					"Developing, supporting, maintaining, and optimising the company website and internal web applications",
					"Designing and developing web-based software solutions",
					"Planning the design and architecture",
					"Developing and connecting databases",
					"Analysing business requirements, and performing cost estimations",
					"Deployment and operation within a Unix-based server environment",
					"Support for questions and issues on the developed websites",
				],
			},
			{
				timespan: "08/2019 – 07/2021",
				employer: "Interhome Group – HHD GmbH, Freiburg in Germany",
				position: "Software Developer",
				tasks: ["Identical tasks and same team as in position 'Web Developer'"],
			},
			{
				timespan: "08/2017 – 07/2019",
				employer: "Interhome Group – HHD GmbH, Freiburg in Germany",
				position: "Trainee | Software Development",
				tasks: ["Identical tasks and same team as in position 'Web Developer'"],
			},
			{
				timespan: "10/2016 – 03/2017",
				employer: "University of Freiburg, Freiburg in Germany",
				position: "Student Assistant and Tutor | Accompanying Seminar to the Lecture 'Introduction to Formal Logic'",
				tasks: [],
			},
			{
				timespan: "10/2015 – 02/2016",
				employer: "University of Freiburg, Freiburg in Germany",
				position: "Student Assistant and Tutor | Accompanying Seminar to the Lecture 'Introduction to Formal Logic'",
				tasks: [],
			},
		],
		education: [
			{
				timespan: "10/2014 – 09/2017",
				institution: "University of Freiburg, Freiburg in Germany",
				topic: "Bachelor of Arts in Philosophy (B.A.)",
				additionalInformation: [
					"Focus area: Formal Logic, Philosophy of Language",
					"Minor subject: English/American Studies",
					"GPA: 1.9",
				],
				degree: "",
			},
			{
				timespan: "10/2013 – 09/2014",
				institution: "University of Freiburg, Freiburg in Germany",
				topic: "Course of Studies: Computer Science",
				additionalInformation: [],
				degree: "",
			},
			{
				timespan: "08/2005 – 07/2013",
				institution: "Secondary School – Gymnasium Borbeck, Essen in Germany",
				topic: "General Higher Qualification for University Entrance",
				additionalInformation: ["GPA: 1.8"],
				degree: "",
			},
		],
		itExperience: {
			feTitle: "Frontend",
			beTitle: "Backend",
			frontend: ["Nuxt.js", "Vue.js", "TypeScript", "JavaScript", "tailwindcss", "CSS", "HTML", "jQuery"],
			backend: [
				"Nuxt.js",
				"Spring Boot",
				"Java",
				"TypeScript",
				"JavaScript",
				"Python",
				"Adobe ColdFusion",
				"MSSQL",
				"Docker",
				"Kubernetes",
				"ArgoCD",
				"Vaadin",
				"redis",
			],
		},
		additionalExperience: [
			{
				title: "Languages",
				values: ["German, native speaker (C2)", "English, business fluent (C1/C2)", "French, basic knowledge (A2)", "Latin"],
			},
			{ title: "Residence permit", values: ["B"] },
		],
	},
	de: {
		headings: {
			title: "Full Stack Web Developer",
			summary: "Kurzfassung",
			cv: "Lebenslauf",
			personalData: "Persönliche Daten",
			professionalExperience: "Berufserfahrung",
			education: "Bildungsweg",
			itExperience: "IT-Kenntnisse",
			additionalExperience: "Weitere Fähigkeiten und Kenntnisse",
		},
		cover: {
			summary:
				"Hoch motivierter Webentwickler mit mehr als 6 Jahren Berufserfahrung. Kompetent in der Gestaltung, Betreuung, und Optimierung von kompletten Unternehmenswebseiten und internen Anwendungen. Geschickt in der Durchführung von Analysen der Geschäftsanforderungen und Implementierung des Serverbetriebs. Engagiert bei der Bereitstellung von hochwertigen digitalen Lösungen. Im Besitz von konzeptioneller Stärke und einem flexiblen, praktischen Ansatz, sowie ausgezeichneten zwischenmenschlichen Fähigkeiten, die eine nahtlose Integration in jedes Team ermöglichen.",
			appendixTitle: "Beilagen",
			appendix: ["Lebenslauf"],
		},
		personalData: {
			pob: {
				title: "Geburtsdatum/-ort",
				value: "01.08.1994 in Essen in Deutschland",
			},
			nationality: {
				title: "Nationalität",
				value: "Deutschland",
			},
			maritalStatus: {
				title: "Zivilstand",
				value: "verheiratet",
			},
			name: "Felix Grafschmidt",
			city: "Nussbaumen AG, CH",
			mail: "felix.grafschmidt@gmail.com",
			phone: "(+41) 774 286063",
		},
		professionalExperience: [
			{
				timespan: "08.2021 – heute",
				employer: "Interhome Group – HHD AG, Opfikon",
				position: "Webentwickler",
				tasks: [
					"Entwicklung, Betreuung, Wartung und Optimierung der Unternehmenswebseite sowie interner Web-Applikationen",
					"Entwurf und Entwicklung webbasierter Softwarelösungen",
					"Planung von Design und Architektur",
					"Entwicklung und Anbindung von Datenbanken",
					"Analyse, Aufwandseinschätzung und Umsetzung von Business Anforderungen",
					"Deployment und Betrieb innerhalb einer Unix-basierten Serverumgebung",
					"Support bei Fragen und Problemen bezüglich der entwickelten Webseiten",
				],
			},
			{
				timespan: "08.2019 – 07.2021",
				employer: "Interhome Group – HHD GmbH, Freiburg in Deutschland",
				position: "Softwareentwickler",
				tasks: ["Identische Tätigkeiten und gleiches Team wie in Position 'Webentwickler'"],
			},
			{
				timespan: "08.2017 – 07.2019",
				employer: "Interhome Group – HHD GmbH, Freiburg in Deutschland",
				position: "Trainee | Softwareentwicklung",
				tasks: ["Identische Tätigkeiten und gleiches Team wie in Position 'Webentwickler'"],
			},
			{
				timespan: "10.2016 – 03.2017",
				employer: "Albert-Ludwigs-Universität Freiburg, Freiburg in Deutschland",
				position: "Studentische Hilfskraft und Tutor | Seminar zur Vorlesung 'Einführung in die Formale Logik'",
				tasks: [],
			},
			{
				timespan: "10.2015 – 02.2016",
				employer: "Albert-Ludwigs-Universität Freiburg, Freiburg in Deutschland",
				position: "Studentische Hilfskraft und Tutor | Seminar zur Vorlesung 'Einführung in die Formale Logik'",
				tasks: [],
			},
		],
		education: [
			{
				timespan: "10.2014 – 09.2017",
				institution: "Albert-Ludwigs-Universität Freiburg, Freiburg in Deutschland",
				topic: "Studiengang: Philosophie",
				additionalInformation: ["Schwerpunkte: Formale Logik und Sprachphilosophie", "Nebenfach: Anglistik", "Abschlussnote: 1,9"],
				degree: "Abschluss: Bachelor of Arts (B.A.)",
			},
			{
				timespan: "10.2013 – 09.2014",
				institution: "Albert-Ludwigs-Universität Freiburg, Freiburg in Deutschland",
				topic: "Studiengang: Informatik",
				additionalInformation: [],
				degree: "",
			},
			{
				timespan: "08.2005 – 07.2013",
				institution: "Gymnasium Borbeck, Essen in Deutschland",
				topic: "",
				additionalInformation: ["Abschlussnote: 1,8"],
				degree: "Abschluss: Allgemeine Hochschulreife",
			},
		],
		itExperience: {
			feTitle: "Frontend",
			beTitle: "Backend",
			frontend: ["Nuxt.js", "Vue.js", "TypeScript", "JavaScript", "tailwindcss", "CSS", "HTML", "jQuery"],
			backend: [
				"Nuxt.js",
				"Spring Boot",
				"Java",
				"TypeScript",
				"JavaScript",
				"Python",
				"Adobe ColdFusion",
				"MSSQL",
				"Docker",
				"Kubernetes",
				"ArgoCD",
				"Vaadin",
				"redis",
			],
		},
		additionalExperience: [
			{
				title: "Sprachen",
				values: [
					"Deutsch, Muttersprache (C2)",
					"Englisch, verhandlungssicher (C1/C2)",
					"Latein, grosses Latinum",
					"Französisch, Grundkenntnisse (A2)",
				],
			},
			{ title: "Aufenthaltsbewilligung", values: ["B"] },
		],
	},
};

export type Data = typeof data;
