import { createApp } from "vue";
import App from "./App.vue";
import "virtual:windi.css";
import { createI18n } from "vue-i18n";

const i18n = createI18n({
	globalInjection: true,
	locale: new URL(window.location.href).searchParams.get("language") || "de",
	availableLocales: ["en", "de"],
	messages: {
		en: {
			title: "CV - Felix Grafschmidt",
			born: "origin",
			dob: "1994/08/01 - Essen",
			nationality: "nationality",
			german: "German",
			english: "English",
			latin: "Latin",
			french: "French",
			maritalStatus: "marital status",
			married: "married",
			nativeSpeaker: "native speaker",
			latinExperience: "7 years (Grosses Latinum)",
			logic: "formal logic",
			linguistics: "linguistics",
			philosophy: "philosophy",
			history: "history",
			videogames: "video games",
			ttgs: "tabletop games",
			programming: "programming",
			reading: "reading",
			aboutMe: "about me",
			contact: "contact",
			skills: "skills",
			hobbies: "interests & hobbies",
			professionalExperience: "professional experience",
			current: "current",
			tasks: "tasks",
			dev1: "development and support of the company website",
			dev2: "development and support of internal web applications",
			trainee: "trainee in software developement department",
			studentAssistant: "student assistant",
			tutor: "tutor at the Philosophical Seminar for the lecture 'Introduction to Formal Logic'",
			education: "academic experience",
			philStudies: "philosophy",
			minor: "minor",
			engStudies: "english and american studies",
			degree: "degree",
			mark: "mark",
			focus: "focus",
			philOfLanguage: "philosophy of language",
			csStudies: "computer science",
			noDegree: "no degree",
			aLevels: "Abitur (general qualification for university entrance)",
			schoolFocus: "advanced courses",
			target: "target position",
			webOrigin: "This CV was originally developed by me as a website. You are currently viewing a PDF created from this website",
			webVersion: "You can find the web version {link}.",
			source: "I will continuously update the web version, both in terms of content and technology. The source code can be found {link}.",
			here: "here",
		},
		de: {
			title: "Lebenslauf - Felix Grafschmidt",
			born: "Geboren",
			dob: "01.08.1994 / Essen",
			nationality: "Staatsangehörigkeit",
			german: "Deutsch",
			english: "Englisch",
			latin: "Latein",
			french: "Französisch",
			maritalStatus: "Familienstand",
			married: "verheiratet",
			nativeSpeaker: "Muttersprache",
			latinExperience: "Grosses Latinum",
			logic: "Formale Logik",
			linguistics: "Linguistik",
			philosophy: "Philosophie",
			history: "Geschichte",
			videogames: "Videospiele",
			ttgs: "Gesellschaftsspiele",
			programming: "Programmieren",
			reading: "Lesen",
			aboutMe: "Über mich",
			contact: "Kontakt",
			skills: "Hauptkompetenzen",
			hobbies: "Interessen & Hobbys",
			professionalExperience: "Beruflicher Werdegang",
			current: "aktuell",
			tasks: "Tätigkeiten",
			dev1: "Entwicklung und Betreuung der Firmenwebsite",
			dev2: "Entwicklung und Betreuung von internen Webapplikationen",
			trainee: "Trainee in der Softwareentwicklung",
			studentAssistant: "Studentische Hilfskraft",
			tutor: "Tutor beim Philosophischen Seminar für die Vorlesung 'Einführung in die Formale Logik'",
			education: "Schulischer Werdegang",
			philStudies: "Studium der Philosophie",
			minor: "Nebenfach",
			engStudies: "Anglistik",
			degree: "Abschluss",
			mark: "Note",
			focus: "Schwerpunkt",
			philOfLanguage: "Sprachphilosophie",
			csStudies: "Studium der Informatik",
			noDegree: "Ohne Abschluss",
			aLevels: "Allgemeine Hochschulreife",
			schoolFocus: "Leistungskurse",
			target: "Angestrebte Position",
			webOrigin:
				"Dieser Lebenslauf wurde ursprünglich von mir als Website entwickelt. Sie betrachten im Moment ein aus dieser Website erstelltes PDF.",
			webVersion: "Die Webversion finden Sie {link}.",
			source: "Ich werde die Webversion laufend updaten, sowohl inhaltlich als auch technisch. Den Quellcode finden Sie {link}.",
			here: "hier",
		},
	},
});

createApp(App).use(i18n).mount("#app");
